### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by UnderratedDev** [teplovs/bon-ui#4]
Hey Ivan,

I really want to contribute to this project. I couldn’t find another way to contact you so
I’m using this issue to log & for contact. Is there a contributing guide, code style for example. And are there any tasks to be done, some sort of list perhaps.

I was planning on making a declarative UI framework for web this year for myself & stumbled across this amazing project, & it’s pretty much what I wanted! So I wish to contribute as much as I can when I have time :)

**Comment by ivteplo** [comment]
Hey @UnderratedDev ! Thanks for helping with improving Bon UI. I'm going to create a guide for development and contributing in a few days.

**Comment by UnderratedDev** [comment]
Awesome!! Can’t wait :)
